"""Core task-session and environment abstractions for RLVR."""

from rlvr_games.core.action_context import (
    ActionContext,
    AgentContextProjector,
    AgentVisibleEvent,
    PublicResetEvent,
    ProjectedActionContext,
)
from rlvr_games.core.async_env import AsyncEnvPool, AsyncResetResult, AsyncStepResult
from rlvr_games.core.async_session import (
    AsyncSessionPool,
    AsyncTaskResetResult,
    AsyncTaskSession,
    AsyncTaskSubmissionResult,
)
from rlvr_games.core.env import TurnBasedEnv
from rlvr_games.core.exceptions import (
    EpisodeFinishedError,
    EnvironmentNotResetError,
    InvalidActionError,
    RLVRGamesError,
)
from rlvr_games.core.messages import (
    ChatMessage,
    DefaultObservationMessageAdapter,
    DefaultObservationMessagePolicy,
    ImageMessagePart,
    MessageRole,
    ObservationMessageAdapter,
    ObservationMessagePolicy,
    TextMessagePart,
)
from rlvr_games.core.protocol import (
    AutoAdvancePolicy,
    Environment,
    ImageRenderer,
    ResetEventPolicy,
    TextRenderer,
)
from rlvr_games.core.rewards import ZeroReward
from rlvr_games.core.rollout import PreparedTurn, build_action_context, prepare_turn
from rlvr_games.core.session import (
    EnvironmentTaskSession,
    TaskInstance,
    TaskResetResult,
    TaskSessionProtocol,
    TaskSubmissionRecord,
    TaskSubmissionResult,
    TaskTrajectory,
    TaskTurn,
)
from rlvr_games.core.session_rollout import TaskSessionPolicy, rollout_task_session
from rlvr_games.core.single_step import (
    PromptRenderer,
    SingleStepTask,
    SingleStepVerifier,
    SingleStepVerifierSession,
    TaskSource,
    VerificationResult,
)
from rlvr_games.core.trajectory import (
    AppliedResetEvent,
    EpisodeTrajectory,
    RecordedResetEvent,
    RecordedTransition,
    ScenarioReset,
    TrajectoryStep,
)
from rlvr_games.core.types import (
    AutoAction,
    EpisodeConfig,
    EpisodeBoundary,
    InvalidActionMode,
    InvalidActionPolicy,
    Observation,
    ParseResult,
    RenderedImage,
    StepResult,
)
from rlvr_games.core.workflow import (
    AsyncWorkflowSession,
    LocalWorkflowSession,
    WorkflowResetResult,
    WorkflowSession,
    WorkflowSessionProtocol,
    WorkflowSubmission,
    WorkflowTurn,
)

__all__ = [
    "ActionContext",
    "AgentContextProjector",
    "AgentVisibleEvent",
    "PublicResetEvent",
    "PreparedTurn",
    "PromptRenderer",
    "ProjectedActionContext",
    "AppliedResetEvent",
    "AsyncEnvPool",
    "AsyncResetResult",
    "AsyncSessionPool",
    "AsyncStepResult",
    "AsyncTaskResetResult",
    "AsyncTaskSession",
    "AsyncTaskSubmissionResult",
    "AsyncWorkflowSession",
    "AutoAction",
    "AutoAdvancePolicy",
    "ChatMessage",
    "DefaultObservationMessageAdapter",
    "DefaultObservationMessagePolicy",
    "Environment",
    "EpisodeConfig",
    "EpisodeBoundary",
    "EpisodeFinishedError",
    "EpisodeTrajectory",
    "EnvironmentTaskSession",
    "EnvironmentNotResetError",
    "ImageRenderer",
    "ImageMessagePart",
    "InvalidActionError",
    "InvalidActionMode",
    "InvalidActionPolicy",
    "LocalWorkflowSession",
    "MessageRole",
    "Observation",
    "ObservationMessageAdapter",
    "ObservationMessagePolicy",
    "ParseResult",
    "RecordedResetEvent",
    "RecordedTransition",
    "RenderedImage",
    "ResetEventPolicy",
    "RLVRGamesError",
    "ScenarioReset",
    "SingleStepTask",
    "SingleStepVerifier",
    "SingleStepVerifierSession",
    "StepResult",
    "TaskInstance",
    "TaskResetResult",
    "TaskSessionProtocol",
    "TaskSessionPolicy",
    "TaskSubmissionRecord",
    "TaskSubmissionResult",
    "TaskTrajectory",
    "TaskTurn",
    "TaskSource",
    "TextRenderer",
    "TextMessagePart",
    "TrajectoryStep",
    "TurnBasedEnv",
    "VerificationResult",
    "ZeroReward",
    "WorkflowResetResult",
    "WorkflowSession",
    "WorkflowSessionProtocol",
    "WorkflowSubmission",
    "WorkflowTurn",
    "build_action_context",
    "prepare_turn",
    "rollout_task_session",
]
