"""Connect 4 scenario initializers."""

from dataclasses import dataclass
from random import Random

from rlvr_games.core.trajectory import ScenarioReset
from rlvr_games.games.connect4.state import (
    Board,
    Connect4State,
    drop_piece,
    make_empty_board,
    normalize_board,
)

STANDARD_CONNECT4_ROWS = 6
STANDARD_CONNECT4_COLUMNS = 7
STANDARD_CONNECT4_CONNECT_LENGTH = 4
DEFAULT_RANDOM_START_MAX_MOVES = 10


@dataclass(slots=True)
class RandomPositionScenario:
    """Scenario that initializes Connect 4 from a random valid position.

    The random start is generated by replaying a deterministic random opening
    sequence from the empty board while avoiding terminal intermediate states.

    Attributes
    ----------
    rows : int
        Number of board rows to initialize.
    columns : int
        Number of board columns to initialize.
    connect_length : int
        Number of contiguous tokens required for a win.
    min_start_moves : int
        Minimum number of opening moves to attempt before reset returns.
    max_start_moves : int
        Maximum number of opening moves to attempt before reset returns.
    """

    rows: int = STANDARD_CONNECT4_ROWS
    columns: int = STANDARD_CONNECT4_COLUMNS
    connect_length: int = STANDARD_CONNECT4_CONNECT_LENGTH
    min_start_moves: int = 0
    max_start_moves: int = DEFAULT_RANDOM_START_MAX_MOVES

    def __post_init__(self) -> None:
        """Validate scenario configuration.

        Raises
        ------
        ValueError
            If the board shape or random opening depth is invalid.
        """
        if self.rows < 1:
            raise ValueError("Connect 4 scenarios require at least one row.")
        if self.columns < 1:
            raise ValueError("Connect 4 scenarios require at least one column.")
        if self.min_start_moves < 0:
            raise ValueError("Connect 4 min_start_moves must be non-negative.")
        if self.max_start_moves < 0:
            raise ValueError("Connect 4 max_start_moves must be non-negative.")
        if self.min_start_moves > self.max_start_moves:
            raise ValueError("Connect 4 min_start_moves cannot exceed max_start_moves.")
        if self.max_start_moves > self.rows * self.columns:
            raise ValueError("Connect 4 max_start_moves cannot exceed board capacity.")

    def reset(self, *, seed: int) -> ScenarioReset[Connect4State]:
        """Create a fresh random Connect 4 episode.

        Parameters
        ----------
        seed : int
            Explicit seed used for deterministic opening generation.

        Returns
        -------
        ScenarioReset[Connect4State]
            Structured reset payload describing the sampled opening sequence.
        """
        rng = Random(seed)
        board = make_empty_board(rows=self.rows, columns=self.columns)
        requested_start_moves = rng.randint(self.min_start_moves, self.max_start_moves)
        applied_start_moves = 0

        for _ in range(requested_start_moves):
            state = Connect4State(
                board=board,
                connect_length=self.connect_length,
            )
            safe_columns = _safe_opening_columns(state=state)
            if not safe_columns:
                break
            chosen_column = rng.choice(safe_columns)
            board, _ = drop_piece(
                board=board,
                column=chosen_column,
                player=state.current_player,
            )
            applied_start_moves += 1

        state = Connect4State(
            board=board,
            connect_length=self.connect_length,
        )
        return ScenarioReset(
            initial_state=state,
            reset_info={
                "scenario": "random_position",
                "seed": seed,
                "rows": state.rows,
                "columns": state.columns,
                "connect_length": state.connect_length,
                "applied_start_moves": applied_start_moves,
                "initial_board": state.board,
            },
        )


@dataclass(slots=True)
class FixedBoardScenario:
    """Scenario that initializes Connect 4 from an explicit board position.

    Attributes
    ----------
    initial_board : Board
        Explicit starting board in top-down row-major order.
    connect_length : int
        Number of contiguous tokens required for a win.
    """

    initial_board: Board
    connect_length: int = STANDARD_CONNECT4_CONNECT_LENGTH

    def __post_init__(self) -> None:
        """Normalize the configured starting board."""
        self.initial_board = normalize_board(rows=self.initial_board)

    def reset(self, *, seed: int) -> ScenarioReset[Connect4State]:
        """Create a fresh Connect 4 episode from the configured board.

        Parameters
        ----------
        seed : int
            Explicit seed forwarded into the reset metadata.

        Returns
        -------
        ScenarioReset[Connect4State]
            Structured reset payload describing the configured board.
        """
        state = Connect4State(
            board=self.initial_board,
            connect_length=self.connect_length,
        )
        return ScenarioReset(
            initial_state=state,
            reset_info={
                "scenario": "fixed_board",
                "seed": seed,
                "rows": state.rows,
                "columns": state.columns,
                "connect_length": state.connect_length,
                "initial_board": state.board,
            },
        )


def normalize_initial_board(*, board: Board) -> Board:
    """Normalize a programmatic or CLI-provided Connect 4 board.

    Parameters
    ----------
    board : Board
        Board-like nested token sequence.

    Returns
    -------
    Board
        Immutable normalized board.
    """
    return normalize_board(rows=board)


def _safe_opening_columns(*, state: Connect4State) -> tuple[int, ...]:
    """Return legal opening columns that keep the sampled start non-terminal."""
    safe_columns: list[int] = []
    for legal_action in state.legal_actions:
        column = int(legal_action) - 1
        candidate_board, _ = drop_piece(
            board=state.board,
            column=column,
            player=state.current_player,
        )
        candidate_state = Connect4State(
            board=candidate_board,
            connect_length=state.connect_length,
        )
        if not candidate_state.is_terminal:
            safe_columns.append(column)
    return tuple(safe_columns)
